baseURL:
languageCode: en-us
title: Austin Freelance Jobs
taxonomies:
  tag: tags
enableRobotsTXT: true
paginate: 1
params:
  #twitter_user: kris_ray
  #twitter_link: https://twitter.com/
  facebook_link: http://www.facebook.com/groups/austinfreelancejobs/
  #instagram_link: https://www.instagram.com/
  #gtm: GTM-123456
  #paid_for: Paid for by Language - Kristopher Ray Creative
  form_endpoint: 123456
markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: true
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
      wrapStandAloneImageWithinParagraph: false
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false
menu:
  main:
    - name: Home
      url: /
      weight: -30
    - name: Browse Freelancers
      url: /#browse
      weight: -20
    - name: Resources
      url: /resources/
      weight: -10
    - name: Job Board
      url: /jobs/
      weight: -5
