site_url: https://austinfreelancejobs.netlify.app
display_url: https://austinfreelancejobs.netlify.app
logo_url: https://austinfreelancejobs.netlify.app/img/login-logo.svg
show_preview_links: false
backend:
  name: git-gateway
  repo: kristopherray/austinfreelancejobs
  branch: master
# This line should *not* be indented
media_folder: "static/img" # Media files will be stored in the repo under images/uploads
public_folder: "/img"
collections:
  - name: "freelancers"
    label: "Freelancers"
    folder: "content/freelancers"
    media_folder: '/static/img/freelancers'
    public_folder: '/img/freelancers'
    filter: {field: "visible", value: true}
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Visible in CMS", name: "visible", widget: hidden, default: true}
      - {label: "Freelancer Entry Name", name: "title", widget: "string"}
      - {label: "Website URL (no HTTPS:// needed)", name: "website", widget: "string"}
      - {label: "LinkedIn URL (INCLUDE https://)", name: "linkedin", widget: "string", required: false}
      - {label: "Profile Image", name: "image", widget: "image", required: false}
      - {label: "Categories", name: "tags", widget: "list", summary: "{{fields.category}}", field: { label: "Category", name: "tag", widget: "string" }}
      - {label: "Body", name: "body", widget: "markdown", required: false}
  - name: "news"
    label: "News"
    folder: "content/news"
    media_folder: '/static/img/news'
    public_folder: '/img/news'
    filter: {field: "visible", value: true}
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Visible in CMS", name: "visible", widget: hidden, default: true}
      - {label: "Draft", name: "draft", widget: "boolean", default: true, required: false}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Description", name: "description", widget: "string", required: false}
      - {label: "Categories", name: "categories", widget: "list", summary: "{{fields.category}}", field: { label: "Category", name: "category", widget: "string" }}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - {label: "Featured Image", name: "image", widget: "image" }
      - {label: "Open Graph Social Preview Image (1200x628)", name: "og_img", widget: "image", required: false }
  - name: "logos"
    label: "Logo Carousel"
    folder: "content/logos"
    media_folder: '/static/img/logos'
    public_folder: '/img/logos'
    filter: {field: "visible", value: true}
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Visible in CMS", name: "visible", widget: hidden, default: true}
      - {label: "Logo Name / Title / Alt Tag", name: "title", widget: "string"}
      - {label: "Logo Image", name: "image", widget: "image" }
      - {label: "Order", name: "weight", widget: "number" }